### ISSUE TITLE
How to ensure the stability of ROS multi communication in large scenarios?

### ISSUE THREAD

**Issue by Fang-1207** [hikashi/TM-RRT_exploration#1]
Hello, the demo video of your actual scene is working in a larger scene. The robot in my current system uses the network provided by the router and can only cover a small space. 
What network communication mode does your system use to cover a large area?
Thanks.

**Comment by hikashi** [comment]
Hi Fang,

I am using a mesh network and WiFi 6 (Asus Router) to extend the network coverage. 
You may try it out if you want to do it in a larger environment.
Hope it helps.

Regards,
Billy

**Comment by Fang-1207** [comment]
> First of all, thank you for your reply. 
Do you use multiple routers to form a mesh network to cover the whole large area?

**Comment by hikashi** [comment]
yes. I used three routers for sufficient area coverage.

**Comment by Fang-1207** [comment]
> yes. I used three routers for sufficient area coverage.

Thanks again.
I will try your method!
