### ISSUE TITLE
how to run a single-robot exploration

### ISSUE THREAD

**Issue by huan-robotics** [hikashi/TM-RRT_exploration#2]
Hello, I hope to run a single-robot exploration, but failed. It would be great if I could get your help. Here are my steps:
1. Downloaded the configuration file for [https://github.com/hikashi/TM-RRT_exploration_Simulation](url),
2. Run `roslaunch ros_3d_multitb3 single_tb3_house4.launch`,
3. Run `roslaunch tmrrt_exploration single_exploration.launch `.
Thanks!

**Comment by hikashi** [comment]
I have made some changes to the old file. 
Please download the latest simulation files and folder from [here](https://github.com/hikashi/TM-RRT_exploration_Simulation
)
you may use back the command you use to run the single robot exploration. 
Do let me know if you still facing the same issue. 
Please copy and paste the error message as it will help me troubleshoot the problem easier.

**Comment by huan-robotics** [comment]
The updated codes run well. Thanks for your help! @hikashi
