### ISSUE TITLE
Question after launch

### ISSUE THREAD

**Issue by Crystal-Biru** [hikashi/TM-RRT_exploration#7]
When I start "roslaunch tmrrt_exploration trio_exploration.launch", no exploration screen appears, only the following information is repeated, I wander is there any error?
[INFO] [1710161258.812695]: waiting for  tb3_1
[INFO] [1710161258.815026]: waiting for  tb3_2
[INFO] [1710161258.816216]: waiting for  tb3_0
[INFO] [1710161258.817273]: Waiting for the map
[INFO] [1710161258.917964]: Waiting for the map
[INFO] [1710161259.019250]: Waiting for the map
[INFO] [1710161259.120321]: Waiting for the map
[INFO] [1710161259.221631]: Waiting for the map
[INFO] [1710161259.322827]: Waiting for the map
[INFO] [1710161259.423866]: Waiting for the map
[INFO] [1710161259.524943]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161259.626148]: Waiting for the map
[INFO] [1710161259.727381]: Waiting for the map
[INFO] [1710161259.828663]: Waiting for the map
[INFO] [1710161259.929902]: Waiting for the map
[INFO] [1710161260.031277]: Waiting for the map
[INFO] [1710161260.132392]: Waiting for the map
[INFO] [1710161260.233544]: Waiting for the map
[INFO] [1710161260.334608]: Waiting for the map
[INFO] [1710161260.435835]: Waiting for the map
[INFO] [1710161260.536919]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161260.638239]: Waiting for the map
[INFO] [1710161260.739713]: Waiting for the map
[INFO] [1710161260.841206]: Waiting for the map
[INFO] [1710161260.942511]: Waiting for the map
[INFO] [1710161261.043817]: Waiting for the map
[INFO] [1710161261.145153]: Waiting for the map
[INFO] [1710161261.252443]: Waiting for the map
[INFO] [1710161261.353614]: Waiting for the map
[INFO] [1710161261.454893]: Waiting for the map
[INFO] [1710161261.556354]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161261.657848]: Waiting for the map
[INFO] [1710161261.759592]: Waiting for the map
[INFO] [1710161261.861269]: Waiting for the map
[INFO] [1710161261.962656]: Waiting for the map
[INFO] [1710161262.064126]: Waiting for the map
[INFO] [1710161262.165549]: Waiting for the map
[INFO] [1710161262.267157]: Waiting for the map
[INFO] [1710161262.368693]: Waiting for the map
[INFO] [1710161262.470001]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161262.571318]: Waiting for the map
[INFO] [1710161262.672677]: Waiting for the map
[INFO] [1710161262.774082]: Waiting for the map
[INFO] [1710161262.875561]: Waiting for the map
[INFO] [1710161262.976867]: Waiting for the map
[INFO] [1710161263.078132]: Waiting for the map
[INFO] [1710161263.179429]: Waiting for the map
[INFO] [1710161263.280741]: Waiting for the map
[INFO] [1710161263.382042]: Waiting for the map
[INFO] [1710161263.483229]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161263.584384]: Waiting for the map
[INFO] [1710161263.685488]: Waiting for the map
[INFO] [1710161263.786626]: Waiting for the map
[INFO] [1710161263.887806]: Waiting for the map
[INFO] [1710161263.989249]: Waiting for the map
[INFO] [1710161264.090558]: Waiting for the map
[INFO] [1710161264.191807]: Waiting for the map
[INFO] [1710161264.292886]: Waiting for the map
[INFO] [1710161264.394048]: Waiting for the map
[INFO] [1710161264.495298]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161264.596532]: Waiting for the map
[INFO] [1710161264.697671]: Waiting for the map
[INFO] [1710161264.798843]: Waiting for the map
[INFO] [1710161264.900247]: Waiting for the map
[INFO] [1710161265.001530]: Waiting for the map
[INFO] [1710161265.102932]: Waiting for the map
[INFO] [1710161265.204368]: Waiting for the map
[INFO] [1710161265.305678]: Waiting for the map
[INFO] [1710161265.406979]: Waiting for the map
[INFO] [1710161265.508351]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161265.609677]: Waiting for the map
[INFO] [1710161265.710910]: Waiting for the map
[INFO] [1710161265.812306]: Waiting for the map
[INFO] [1710161265.913754]: Waiting for the map
[INFO] [1710161266.015110]: Waiting for the map
[INFO] [1710161266.116642]: Waiting for the map
[INFO] [1710161266.218190]: Waiting for the map
[INFO] [1710161266.319547]: Waiting for the map
[INFO] [1710161266.421383]: Waiting for the map
[INFO] [1710161266.528593]: Waiting for the map
[]
waiting for the boundary points to be calculated
[INFO] [1710161266.630220]: Waiting for the map
[INFO] [1710161266.731778]: Waiting for the map
[INFO] [1710161266.833210]: Waiting for the map
[INFO] [1710161266.934684]: Waiting for the map
[INFO] [1710161267.036261]: Waiting for the map
[INFO] [1710161267.137801]: Waiting for the map
[INFO] [1710161267.239322]: Waiting for the map
[INFO] [1710161267.340819]: Waiting for the map
[INFO] [1710161267.442239]: Waiting for the map
[INFO] [1710161267.543644]: Waiting for the map
[]

**Comment by hikashi** [comment]
Hi Crystal-Biru,

I believe the merged map is not available for the exploration stack. 
Can you check whether the merge map is available?
You may check using rostopic echo or hz.

**Comment by Crystal-Biru** [comment]
After using rostopic hz, only 'no new messages" showed:
zbr@zbr-HKF-WXX:~/catkin_explore$ rostopic hz map
subscribed to [/map]
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages

**Comment by hikashi** [comment]
Most probably you did not run the map merger or something wrong with it. 
Please check whether it is running or not. 

More details of the map merger can be found [here](http://wiki.ros.org/multirobot_map_merge).

**Comment by Crystal-Biru** [comment]
Thank you for your reply! I tried to use the code and follow the instructions from [TM-RRT_exploration_Simulation](https://github.com/hikashi/TM-RRT_exploration_Simulation), and the project ran successfully.

**Comment by hikashi** [comment]
Great!
